POST http://localhost:3000/books
Content-Type: application/json

{
   "title": "Animal farm",
   "ISBN": "874737",
   "publishedDate": 2008,
   "author": "Robert Boyer"
}

###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/0.6801036753246139

###
PUT http://localhost:3000/books/0.6801036753246139
Content-Type: application/json

{
  "author": "James Adam"
}

###
DELETE http://localhost:3000/books/0.6801036753246139